apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "stickerstore.webstore.name" . }}
  labels:
    app: {{ template "stickerstore.webstore.name" . }}
    chart: {{ template "stickerstore.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "stickerstore.webstore.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "stickerstore.webstore.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
      - name:  "{{ .Values.image.pullSecret }}"
      env:
      - name: ORDER_SERVICE
        value: "http://orderservice/api/order"
      - name: STATUS_SERVICE
        value: "http://statusservice/api/status"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
